version: '2'
services:
        vas_app:
                build: .
                ports:
                 - "8080:8080"
                 - "8070:8070"
                 - "9000:9000"
                 - "10000:80"
                volumes:
                 - .:/home/
                restart: always
                #working_dir: $HOME/vas_app/
                command: /home/run_startup_scripts.sh
